syn match markdownIgnore '._.'
"syn match markdownIgnore '[\w,]_[\w,]'
syn match markdownIgnore '[^* ]\*'
"syn match markdownItalic '_'
"syn match markdownItalicDelimiter ' '
syn match markdownBold '\*{2}'
syn match markdownBoldDelimiter ' '
